name: guidi_tu
description: Guidi Tu, un videogioco per selezionare chi guida stasera e chi invece beve.

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number is used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
# In Windows, build-name is used as the major, minor, and patch parts
# of the product and file versions while build-number is used as the build suffix.
version: 0.7.0+13

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: ^3.10.1

# Dependencies specify other packages that your package needs in order to work.
# To automatically upgrade your package dependencies to the latest versions
# consider running `flutter pub upgrade --major-versions`. Alternatively,
# dependencies can be manually updated by changing the version numbers below to
# the latest version available on pub.dev. To see which dependencies have newer
# versions available, run `flutter pub outdated`.
dependencies:
  flutter:
    sdk: flutter
  collection: ^1.17.1
  intl: ^0.18.1
  shared_preferences: ^2.2.0
  flame: ^1.8.1
  flame_forge2d: ^0.14.1
  sensors_plus: ^3.0.2
  flutter_carousel_widget: ^2.0.4
  flutter_markdown: ^0.6.15+1

dev_dependencies:
  flutter_test:
    sdk: flutter
  dart_code_metrics: ^5.7.5
  dart_code_metrics_presets: ^1.8.0
  flutter_lints: ^2.0.2
  flutter_launcher_icons: ^0.13.1
  flutter_native_splash: ^2.3.1

flutter:
  uses-material-design: true
  assets:
    - assets/images/title/
    - assets/images/players/white/
    - assets/images/players/color/
    - assets/images/players/inverted/
    - assets/images/battleship/
    - assets/images/battleship/interstitial/
    - assets/images/battleship/duck/
    - assets/images/battleship/boat/
    - assets/images/battleship/buoy/
    - assets/images/boules/
    - assets/images/morra/hands/
    - assets/images/morra/interstitial/
    - assets/images/ouija/
    - assets/images/ouija/interstitial/
    - assets/images/shot/
    - assets/images/shot/interstitial/
    - assets/images/steady_hand/
    - assets/images/stopwatch/
    - assets/images/stopwatch/interstitial/
    - assets/images/straws/
    - assets/images/tutorial/
    - assets/images/rps/hands/
    - assets/images/rps/interstitial/
  fonts:
    - family: Signika
      fonts:
        - asset: assets/fonts/Signika-VariableFont_wght.ttf
    - family: LexendDeca
      fonts:
        - asset: assets/fonts/LexendDeca-VariableFont_wght.ttf

# dart run flutter_launcher_icons
flutter_launcher_icons:
  image_path: assets/icons/icon.png
  android: true
  ios: true
  adaptive_icon_background: "#2f2735"
  adaptive_icon_foreground: assets/icons/icon_transparent.png

# dart run flutter_native_splash:create
flutter_native_splash:
  color: "#2f2735"
  fullscreen: true
